// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyFxYqbH2gYKazk0gX1Rikz2E37Erd7jA',
    appId: '1:245553217422:web:281dca96c17d6cf3a92edf',
    messagingSenderId: '245553217422',
    projectId: 'flutterproject1-f79b8',
    authDomain: 'flutterproject1-f79b8.firebaseapp.com',
    storageBucket: 'flutterproject1-f79b8.appspot.com',
    measurementId: 'G-2KCN8WPXLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADKFDRZELqE1pwNXRf_G9NLPZ8eIkYmo8',
    appId: '1:245553217422:android:5e2e4ac37526de20a92edf',
    messagingSenderId: '245553217422',
    projectId: 'flutterproject1-f79b8',
    storageBucket: 'flutterproject1-f79b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUYBvsaXbV2hA7LfowGfnZsqKAFM_4sG4',
    appId: '1:245553217422:ios:b1b63239a1a5623fa92edf',
    messagingSenderId: '245553217422',
    projectId: 'flutterproject1-f79b8',
    storageBucket: 'flutterproject1-f79b8.appspot.com',
    iosBundleId: 'com.example.prjUasD124',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUYBvsaXbV2hA7LfowGfnZsqKAFM_4sG4',
    appId: '1:245553217422:ios:b1b63239a1a5623fa92edf',
    messagingSenderId: '245553217422',
    projectId: 'flutterproject1-f79b8',
    storageBucket: 'flutterproject1-f79b8.appspot.com',
    iosBundleId: 'com.example.prjUasD124',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyFxYqbH2gYKazk0gX1Rikz2E37Erd7jA',
    appId: '1:245553217422:web:5adb5c3fd7f4d31ba92edf',
    messagingSenderId: '245553217422',
    projectId: 'flutterproject1-f79b8',
    authDomain: 'flutterproject1-f79b8.firebaseapp.com',
    storageBucket: 'flutterproject1-f79b8.appspot.com',
    measurementId: 'G-VK7W4G6NRX',
  );
}
